### ISSUE TITLE
Kernel panic

### ISSUE THREAD

**Issue by aleksei-udalov** [terence-deng/mt7601u#9]
Hi, at first thank you for this driver. I used it about year ago with no issues. 

But now I has 2 notebooks both with Debian Jessie. On Thinkpad I get kernel panic when insert mt7601 into usb. On Packard Bell kernel panic occurs when trying to load some web page with wget or Firefox, but ping work. Embedded wifi modules both work fine.

 uname -a
Linux machine_name 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u1 (2017-02-22) x86_64 GNU/Linux

![zcy5zov0hly](https://cloud.githubusercontent.com/assets/14933849/24981128/47532b5e-1fec-11e7-99cd-5e59190b795a.jpg)

Do you think I need to roll back to 3.13?

**Comment by terence-deng** [comment]
Hi, I would roll back to previous version if kernel panic occurred in new version.

**Comment by aleksei-udalov** [comment]
I found out that driver works on Debian with 3.16.7-ckt25-2 kernel.
